### ISSUE TITLE
secret diceの挙動について

### ISSUE THREAD

**Issue by inatatsu-tatsuhiro** [Rin0530/TRPGPlugin#1]
クトゥルフ神話TRPGではシークレットダイスはKPのみ確認で振ったPLに出目は公開されません。

**Comment by Rin0530** [comment]
KPがシークレットダイスを振った場合はPLには公開されません
また、PLがシークレットダイスを振った場合は振ったPL本人とKPに出目が表示されるようになっています

**Comment by inatatsu-tatsuhiro** [comment]
クトゥルフ神話TRPGのルールでは、PLがシークレットダイスを必要とする場合(心理学ロール等)ダイスの出目・成功か失敗かはPLに秘匿され、KPよりダイスの結果により得ることができた情報のみが共有されます。

**Comment by inatatsu-tatsuhiro** [comment]
基本KP以外がシークレットダイスを振ることはないため、コマンド宣言をKPが行う運用であれば実装的には問題ないですが、シークレットダイスを使用するPLがコマンド宣言を行う運用であれば、PLに出目、判定結果が共有されてしまうという問題が発生します。

**Comment by Rin0530** [comment]
そうなんですね、ありがとうございます
修正しました
